---
version: 2
publish: &publish
  working_directory: ~/my-app
  docker:
    - image: circleci/node:10.4.1
  steps:
    - checkout

    - run:
        name: Installing dependencies
        command: yarn
    - run:
        name: prepare expo
        command: |
          echo 'export PATH=$(yarn global bin):$PATH' >> $BASH_ENV
          source $BASH_ENV
          yarn global add expo-cli

    - run:
        name: Login into Expo
        command: expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD

    - run:
        name: Publish to Expo
        command: expo publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL

jobs:
  publish_to_expo_staging:
    environment:
      EXPO_RELEASE_CHANNEL: staging
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish

workflows:
  version: 2
  my_app:
    jobs:
      - publish_to_expo_staging:
          filters:
            branches:
              only: development
      - publish_to_expo_prod:
          filters:
            branches:
              only: master